apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flappy-fun
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flappy-fun
                port:
                  number: 80
